# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#import images

class Ui_game_window(object):
    def setupUi(self, game_window):
        game_window.setObjectName("game_window")
        game_window.resize(952, 489)
        game_window.setStyleSheet("")
        self.background_image = QtWidgets.QLabel(game_window)
        self.background_image.setGeometry(QtCore.QRect(-2, 0, 961, 491))
        self.background_image.setBaseSize(QtCore.QSize(720, 420))
        self.background_image.setStyleSheet("image: url(:/newPrefix/photo_2022-11-22_18-17-45.jpg);")
        self.background_image.setText("")
        self.background_image.setPixmap(QtGui.QPixmap(":/newPrefix/photo_2022-11-22_18-17-45.jpg"))
        self.background_image.setObjectName("background_image")
        self.button_buy_place_for_attraction = QtWidgets.QPushButton(game_window)
        self.button_buy_place_for_attraction.setGeometry(QtCore.QRect(750, 410, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.button_buy_place_for_attraction.setFont(font)
        self.button_buy_place_for_attraction.setMouseTracking(False)
        self.button_buy_place_for_attraction.setTabletTracking(False)
        self.button_buy_place_for_attraction.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_buy_place_for_attraction.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_buy_place_for_attraction.setStyleSheet("\n"
"QPushButton {\n"
"    border-style: outset;\n"
"    border: 2px solid #111;\n"
"    border-color: rgb(167, 167, 167);\n"
"    background-color: rgb(190, 250, 134);\n"
"\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:  rgb(163, 250, 92);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(170, 223, 120);\n"
"    }")
        self.button_buy_place_for_attraction.setIconSize(QtCore.QSize(16, 16))
        self.button_buy_place_for_attraction.setFlat(False)
        self.button_buy_place_for_attraction.setObjectName("button_buy_place_for_attraction")
        self.balance_text = QtWidgets.QTextBrowser(game_window)
        self.balance_text.setGeometry(QtCore.QRect(10, 440, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.balance_text.setFont(font)
        self.balance_text.setStyleSheet("background-color:rgb(251, 204, 32, 85%);\n"
"border: 2px solid #111;\n"
"border-color: rgb(167, 167, 167);\n"
"")
        self.balance_text.setObjectName("balance_text")

        self.button_attraction_1 = QtWidgets.QPushButton(game_window)
        self.button_attraction_1.setGeometry(QtCore.QRect(180, 20, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.button_attraction_1.setFont(font)
        self.button_attraction_1.setMouseTracking(False)
        self.button_attraction_1.setTabletTracking(False)
        self.button_attraction_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_attraction_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_attraction_1.setStyleSheet("\n"
"QPushButton {\n"
"    border-style: outset;\n"
"    border: 2px solid #111;\n"
"    border-color: rgb(167, 167, 167);\n"
"    background-color:rgb(0, 255, 204);\n"
"\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:  rgb(0, 212, 254);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(0, 206, 165);\n"
"    }")
        self.button_attraction_1.setIconSize(QtCore.QSize(16, 16))
        self.button_attraction_1.setFlat(False)
        self.button_attraction_1.setObjectName("button_attraction_1")
        self.button_visitor = QtWidgets.QPushButton(game_window)
        self.button_visitor.setGeometry(QtCore.QRect(300, 320, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)

        self.button_return_to_menu = QtWidgets.QPushButton(game_window)
        self.button_return_to_menu.setGeometry(QtCore.QRect(10, 10, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.button_return_to_menu.setFont(font)
        self.button_return_to_menu.setMouseTracking(False)
        self.button_return_to_menu.setTabletTracking(False)
        self.button_return_to_menu.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_return_to_menu.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_return_to_menu.setStyleSheet("\n"
                                               "QPushButton {\n"
                                               "    border-style: outset;\n"
                                               "    border: 2px solid #111;\n"
                                               "    border-color: rgb(167, 167, 167);\n"
                                               "    background-color:rgb(190, 190, 190, 80%);\n"
                                               "\n"
                                               "    }\n"
                                               "\n"
                                               "QPushButton:hover {\n"
                                               "    background:  rgb(120, 120, 120);\n"
                                               "    }\n"
                                               "\n"
                                               "QPushButton:pressed {\n"
                                               "    border-style: inset;\n"
                                               "    background: rgb(145, 145, 145);\n"
                                               "    }")
        self.button_return_to_menu.setIconSize(QtCore.QSize(16, 16))
        self.button_return_to_menu.setFlat(False)
        self.button_return_to_menu.setObjectName("button_attraction_1")
        self.button_visitor = QtWidgets.QPushButton(game_window)
        self.button_visitor.setGeometry(QtCore.QRect(300, 320, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)

        self.button_visitor.setFont(font)
        self.button_visitor.setMouseTracking(False)
        self.button_visitor.setTabletTracking(False)
        self.button_visitor.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_visitor.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_visitor.setStyleSheet("\n"
"QPushButton {\n"
"    border-style: outset;\n"
"    border-radius: 12px;\n"
"    border: 2px solid #111;\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 231, 106);\n"
"\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:rgb(255, 200, 105)\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(213, 193, 88);\n"
"    }")
        self.button_visitor.setText("")
        self.button_visitor.setIconSize(QtCore.QSize(16, 16))
        self.button_visitor.setFlat(False)
        self.button_visitor.setObjectName("button_visitor")
        self.button_attraction_3 = QtWidgets.QPushButton(game_window)
        self.button_attraction_3.setGeometry(QtCore.QRect(820, 20, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.button_attraction_3.setFont(font)
        self.button_attraction_3.setMouseTracking(False)
        self.button_attraction_3.setTabletTracking(False)
        self.button_attraction_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_attraction_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_attraction_3.setStyleSheet("\n"
"QPushButton {\n"
"    border-style: outset;\n"
"    border: 2px solid #111;\n"
"    border-color: rgb(167, 167, 167);\n"
"    background-color:rgb(0, 255, 204);\n"
"\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:  rgb(0, 212, 254);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(0, 206, 165);\n"
"    }")
        self.button_attraction_3.setIconSize(QtCore.QSize(16, 16))
        self.button_attraction_3.setFlat(False)
        self.button_attraction_3.setObjectName("button_attraction_3")
        self.button_attraction_2 = QtWidgets.QPushButton(game_window)
        self.button_attraction_2.setGeometry(QtCore.QRect(180, 100, 121, 111))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.button_attraction_2.setFont(font)
        self.button_attraction_2.setMouseTracking(False)
        self.button_attraction_2.setTabletTracking(False)
        self.button_attraction_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_attraction_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_attraction_2.setStyleSheet("\n"
"QPushButton {\n"
"    border-style: outset;\n"
"    border: 2px solid #111;\n"
"    border-color: rgb(167, 167, 167);\n"
"    background-color:rgb(0, 255, 204);\n"
"\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:  rgb(0, 212, 254);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(0, 206, 165);\n"
"    }")
        self.button_attraction_2.setIconSize(QtCore.QSize(16, 16))
        self.button_attraction_2.setFlat(False)
        self.button_attraction_2.setObjectName("button_attraction_2")
        self.button_place_for_attraction = QtWidgets.QPushButton(game_window)
        self.button_place_for_attraction.setEnabled(False)
        self.button_place_for_attraction.setGeometry(QtCore.QRect(820, 90, 121, 101))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.button_place_for_attraction.setFont(font)
        self.button_place_for_attraction.setMouseTracking(False)
        self.button_place_for_attraction.setTabletTracking(False)
        self.button_place_for_attraction.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_place_for_attraction.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_place_for_attraction.setStyleSheet("\n"
"QPushButton {\n"
"    border-style: outset;\n"
"    border: 2px solid #111;\n"
"    border-color: rgb(167, 167, 167);\n"
"    background-color:rgb(0, 255, 204);\n"
"\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:  rgb(0, 212, 254);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(0, 206, 165);\n"
"    }")
        self.button_place_for_attraction.setIconSize(QtCore.QSize(16, 16))
        self.button_place_for_attraction.setFlat(False)
        self.button_place_for_attraction.setObjectName("button_place_for_attraction")
        self.button_place_for_attraction_2 = QtWidgets.QPushButton(game_window)
        self.button_place_for_attraction_2.setEnabled(False)
        self.button_place_for_attraction_2.setGeometry(QtCore.QRect(820, 200, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.button_place_for_attraction_2.setFont(font)
        self.button_place_for_attraction_2.setMouseTracking(False)
        self.button_place_for_attraction_2.setTabletTracking(False)
        self.button_place_for_attraction_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_place_for_attraction_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_place_for_attraction_2.setStyleSheet("\n"
"QPushButton {\n"
"    border-style: outset;\n"
"    border: 2px solid #111;\n"
"    border-color: rgb(167, 167, 167);\n"
"    background-color:rgb(0, 255, 204);\n"
"\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:  rgb(0, 212, 254);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(0, 206, 165);\n"
"    }")
        self.button_place_for_attraction_2.setIconSize(QtCore.QSize(16, 16))
        self.button_place_for_attraction_2.setFlat(False)
        self.button_place_for_attraction_2.setObjectName("button_place_for_attraction_2")

        self.retranslateUi(game_window)
        QtCore.QMetaObject.connectSlotsByName(game_window)

    def retranslateUi(self, game_window):
        _translate = QtCore.QCoreApplication.translate
        game_window.setWindowTitle(_translate("game_window", "Парк развлечений"))
        self.button_buy_place_for_attraction.setText(_translate("game_window", "Купить место для\n"
" аттракциона"))
        self.balance_text.setHtml(_translate("game_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Verdana\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">Баланс: 220$</span></p></body></html>"))
        self.button_return_to_menu.setText(_translate("game_window", "Esq"))
        self.button_attraction_1.setText(_translate("game_window", "Аттракцион1"))
        self.button_attraction_3.setText(_translate("game_window", "Аттракцион3"))
        self.button_attraction_2.setText(_translate("game_window", "Аттракцион2"))
        self.button_place_for_attraction.setText(_translate("game_window", "Место для\n"
" аттракциона1"))
        self.button_place_for_attraction_2.setText(_translate("game_window", "Место для\n"
" аттракциона2"))
from windows import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    game_window = QtWidgets.QDialog()
    ui = Ui_game_window()
    ui.setupUi(game_window)
    game_window.show()
    sys.exit(app.exec_())
