# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window2(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(720, 425)
        main_window.setStyleSheet("background-color: rgb(234, 254, 217);")
        self.enter_id_text = QtWidgets.QLabel(main_window)
        self.enter_id_text.setGeometry(QtCore.QRect(255, 50, 210, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enter_id_text.setFont(font)
        self.enter_id_text.setObjectName("enter_id_text")
        self.button_enter = QtWidgets.QPushButton(main_window)
        self.button_enter.setGeometry(QtCore.QRect(200, 140, 320, 80))

        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        self.button_enter.setFont(font)
        self.button_enter.setMouseTracking(False)
        self.button_enter.setTabletTracking(False)
        self.button_enter.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_enter.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_enter.setStyleSheet("\n"
                                        "QPushButton {\n"
                                        "    border-style: outset;\n"
                                        "    border: 2px solid #111;\n"
                                        "    border-color: rgb(167, 167, 167);\n"
                                        "    background-color: rgb(190, 250, 134);\n"
                                        "    padding: 4px;\n"
                                        "    }\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background:  rgb(163, 250, 92);\n"
                                        "    }\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    border-style: inset;\n"
                                        "    background: rgb(170, 223, 120);\n"
                                        "    }")
        self.button_enter.setIconSize(QtCore.QSize(16, 16))
        self.button_enter.setFlat(False)
        self.button_enter.setObjectName("button_enter")
        self.button_exit_and_save = QtWidgets.QPushButton(main_window)
        self.button_exit_and_save.setGeometry(QtCore.QRect(200, 250, 320, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(190, 250, 134))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)

        self.button_exit_and_save.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        self.button_exit_and_save.setFont(font)
        self.button_exit_and_save.setMouseTracking(False)
        self.button_exit_and_save.setTabletTracking(False)
        self.button_exit_and_save.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_exit_and_save.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_exit_and_save.setStyleSheet("\n"
                                          "QPushButton {\n"
                                          "    border-style: outset;\n"
                                          "    border: 2px solid #111;\n"
                                          "    border-color: rgb(167, 167, 167);\n"
                                          "    background-color: rgb(190, 250, 134);\n"
                                          "    padding: 4px;\n"
                                          "    }\n"
                                          "\n"
                                          "QPushButton:hover {\n"
                                          "    background:  rgb(163, 250, 92);\n"
                                          "    }\n"
                                          "\n"
                                          "QPushButton:pressed {\n"
                                          "    border-style: inset;\n"
                                          "    background: rgb(170, 223, 120);\n"
                                          "    }")
        self.button_exit_and_save.setIconSize(QtCore.QSize(16, 16))
        self.button_exit_and_save.setFlat(False)
        self.button_exit_and_save.setObjectName("button_enter_2")

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Парк развлечений"))
        self.enter_id_text.setText(_translate("main_window", "Парк развлечений"))
        self.button_enter.setText(_translate("main_window", "Продолжить игру"))
        self.button_exit_and_save.setText(_translate("main_window", "Выйти и сохранить"))





