# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_new_game_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_start_new_game_window(object):
    def setupUi(self, start_new_game_window):
        start_new_game_window.setObjectName("start_new_game_window")
        start_new_game_window.resize(720, 417)
        start_new_game_window.setStyleSheet("background-color: rgb(234, 254, 217);")
        self.park_name_plainTextEdit = QtWidgets.QPlainTextEdit(start_new_game_window)
        self.park_name_plainTextEdit.setGeometry(QtCore.QRect(10, 50, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.park_name_plainTextEdit.setFont(font)
        self.park_name_plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.park_name_plainTextEdit.setObjectName("park_name_plainTextEdit")
        self.park_name_text = QtWidgets.QLabel(start_new_game_window)
        self.park_name_text.setGeometry(QtCore.QRect(10, 20, 210, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.park_name_text.setFont(font)
        self.park_name_text.setObjectName("park_name_text")
        self.your_nickname_text = QtWidgets.QLabel(start_new_game_window)
        self.your_nickname_text.setGeometry(QtCore.QRect(10, 110, 210, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.your_nickname_text.setFont(font)
        self.your_nickname_text.setObjectName("your_nickname_text")
        self.nickname_plainTextEdit = QtWidgets.QPlainTextEdit(start_new_game_window)
        self.nickname_plainTextEdit.setGeometry(QtCore.QRect(10, 140, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.nickname_plainTextEdit.setFont(font)
        self.nickname_plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nickname_plainTextEdit.setObjectName("nickname_plainTextEdit")
        self.button_play = QtWidgets.QPushButton(start_new_game_window)
        self.button_play.setGeometry(QtCore.QRect(200, 320, 320, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(190, 250, 134))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 250, 134))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 250, 134))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 250, 134))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 250, 134))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 250, 134))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 250, 134))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 250, 134))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 250, 134))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.button_play.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        self.button_play.setFont(font)
        self.button_play.setMouseTracking(False)
        self.button_play.setTabletTracking(False)
        self.button_play.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_play.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_play.setStyleSheet("\n"
"QPushButton {\n"
"    border-style: outset;\n"
"    border: 2px solid #111;\n"
"    border-color: rgb(167, 167, 167);\n"
"    background-color: rgb(190, 250, 134);\n"
"    padding: 4px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background:  rgb(163, 250, 92);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: rgb(170, 223, 120);\n"
"    }")
        self.button_play.setIconSize(QtCore.QSize(16, 16))
        self.button_play.setFlat(False)
        self.button_play.setObjectName("button_play")

        self.retranslateUi(start_new_game_window)
        QtCore.QMetaObject.connectSlotsByName(start_new_game_window)

    def retranslateUi(self, start_new_game_window):
        _translate = QtCore.QCoreApplication.translate
        start_new_game_window.setWindowTitle(_translate("start_new_game_window", "Парк развлечений"))
        self.park_name_text.setText(_translate("start_new_game_window", "Название парка:"))
        self.your_nickname_text.setText(_translate("start_new_game_window", "Ваш никнейм:"))
        self.button_play.setText(_translate("start_new_game_window", "Играть"))
